name: CI

on: [pull_request]

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2

      - name: Composer update
        run: composer update --ignore-platform-reqs --no-interaction --prefer-stable

      - name: Prepare TYPO3 extension path
        run: |
          mkdir -p public/typo3conf/ext/
          if [ ! -L public/typo3conf/ext/page_warmup ]; then ln -snvf ../../../. public/typo3conf/ext/page_warmup; fi

      - name: Functional Tests
        env:
          typo3DatabaseDriver: pdo_sqlite
          typo3DatabaseName: typo3
        run: vendor/bin/phpunit -c .github/phpunit.functional.xml
